# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [10]:
import numpy as np

#### Set the seed to 0

In [36]:
import numpy as np
np.random.seed(0)

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
array=np.ones(10)
print("An array of 10 ones:")
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [7]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50 (in order)

In [15]:
array=np.arange(10,51,1)
print(array) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [16]:
array=np.arange(0,51,2)
print(array) 

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


#### Create a 5x5 matrix with values ranging from 0 to 8

In [20]:
np.arange(0,9).reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [21]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [22]:
np.random.randint(0,1)


0

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [25]:
rand_num = np.random.normal(0,1,25).reshape((5,5))
print(rand_num)

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]


#### Create the following matrix (hint: use `linspace` with `reshape`):

In [51]:
np.linspace(0.01, 1)

array([0.01      , 0.03020408, 0.05040816, 0.07061224, 0.09081633,
       0.11102041, 0.13122449, 0.15142857, 0.17163265, 0.19183673,
       0.21204082, 0.2322449 , 0.25244898, 0.27265306, 0.29285714,
       0.31306122, 0.33326531, 0.35346939, 0.37367347, 0.39387755,
       0.41408163, 0.43428571, 0.4544898 , 0.47469388, 0.49489796,
       0.51510204, 0.53530612, 0.5555102 , 0.57571429, 0.59591837,
       0.61612245, 0.63632653, 0.65653061, 0.67673469, 0.69693878,
       0.71714286, 0.73734694, 0.75755102, 0.7777551 , 0.79795918,
       0.81816327, 0.83836735, 0.85857143, 0.87877551, 0.89897959,
       0.91918367, 0.93938776, 0.95959184, 0.97979592, 1.        ])

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
mat[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [32]:
 mat[3,4]


20

```python 
[Output]:
20
```

In [33]:
mat[0:3,1:2]


array([[ 2],
       [ 7],
       [12]])

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [34]:
mat[4]


array([21, 22, 23, 24, 25])

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [35]:
mat[3:]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

### Conditional Indexing (AKA fancy indexing)

In [10]:
import numpy as np
np.random.seed(0)

In [11]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

#### Select all rows where the first element is less than or equal to 20.

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Replace all negative elements with 0.

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Calculate the sum of all elements that are less than or equal to 5.

Expected result: `5`

### Calculate the mean of all elements in the last column.

Expected result: `20.2`

#### Count the number of elements that are not equal to 0.

Expected result: `21`

#### Replace all elements equal to the maximum value of the matrix with 0.

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Math on rows and columns

#### Add 5 to a all mat elements

In [42]:
mat = mat + 5

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### Get the sum of all the values in mat

In [40]:
print(np.sum(mat))


325


In [48]:
mat.std()


7.211102550927978

#### Get the sum of all the columns in mat

In [39]:
print(np.sum(mat, axis=0))


[55 60 65 70 75]


#### Get the sum of all the rows in mat

In [41]:
print(np.sum(mat, axis=1))


[ 15  40  65  90 115]


# Great Job!